/**
 * Token build. Resolves {core.path} refs in semantic.json, applies theme overrides,
 * emits CSS custom properties + typed constants.
 *
 * Run: pnpm tokens
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = fileURLToPath(new URL('.', import.meta.url))
const core = JSON.parse(readFileSync(join(here, 'core.json'), 'utf8'))
const semantic = JSON.parse(readFileSync(join(here, 'semantic.json'), 'utf8'))

const get = (obj: any, path: string) => path.split('.').reduce((o, k) => o?.[k], obj)

/** Resolve {core.path} references, recursively, with cycle detection. */
function resolve(value: string, seen = new Set<string>()): string {
  const m = /^\{(.+)\}$/.exec(value)
  if (!m) return value
  const path = m[1]!
  if (seen.has(path)) throw new Error(`Token cycle: ${[...seen, path].join(' → ')}`)
  const hit = get(core, path) ?? get(semantic, path)
  if (hit === undefined) throw new Error(`Unknown token reference: {${path}}`)
  return typeof hit === 'string' ? resolve(hit, new Set([...seen, path])) : String(hit)
}

/** semantic.json is two levels deep: group → key. Emits --group-key. */
function flatten(obj: Record<string, any>): Record<string, string> {
  const out: Record<string, string> = {}
  for (const [group, entries] of Object.entries(obj)) {
    if (group.startsWith('$') || typeof entries !== 'object') continue
    for (const [key, val] of Object.entries(entries as Record<string, unknown>)) {
      if (key.startsWith('$') || typeof val !== 'string') continue
      out[`--${group}-${key}`] = resolve(val)
    }
  }
  return out
}

const base = flatten(semantic)

let css = '/* GENERATED by packages/tokens/build.ts — do not edit */\n:root {\n'
for (const [k, v] of Object.entries(base)) css += `  ${k}: ${v};\n`
css += '}\n\n'

// Theme blocks
const themeDir = join(here, 'themes')
for (const file of readdirSync(themeDir).filter(f => f.endsWith('.json'))) {
  const theme = JSON.parse(readFileSync(join(themeDir, file), 'utf8'))
  const slug = file.replace(/\.json$/, '')
  css += `/* ${theme.name} — ${theme.description} */\n[data-theme="${slug}"] {\n`
  for (const [path, val] of Object.entries(theme.overrides as Record<string, string>)) {
    css += `  --${path.replace('.', '-')}: ${resolve(val)};\n`
  }
  css += '}\n\n'
}

// Accessibility + performance modes
css += `@media (prefers-reduced-motion: reduce) {
  :root { ${Object.keys(base).filter(k => k.startsWith('--motion-') && !k.includes('ease'))
    .map(k => `${k}: 0ms;`).join(' ')} }
}

[data-motion="fast"] {
${Object.entries(base).filter(([k]) => k.startsWith('--motion-') && !k.includes('ease'))
  .map(([k, v]) => `  ${k}: calc(${v} * 0.5);`).join('\n')}
}

/* Four-colour deck */
[data-deck="four-colour"] {
  --card-suit-diamond: ${resolve('{color.suit.diamond}')};
  --card-suit-club: ${resolve('{color.suit.club}')};
}
`

mkdirSync(join(here, 'dist'), { recursive: true })
writeFileSync(join(here, 'dist/tokens.css'), css)

const names = Object.keys(base)
writeFileSync(join(here, 'dist/tokens.ts'),
  `/* GENERATED */\nexport const tokens = ${JSON.stringify(base, null, 2)} as const\n` +
  `export type TokenName = keyof typeof tokens\n`)

console.log(`tokens: ${names.length} properties, ${readdirSync(themeDir).length} themes → dist/`)
